### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by bradleygurwin** [alessandrofama/FMOD-Audio-Importer#1]
Hi Alessandro,

I'm wondering how to actually get this tool working in my FMOD project. Should this be loaded in as a script? Something else? 

I'm new to FMOD so I apologize if the answer is obvious. Thank you!

Cheers,
Bradley

**Comment by alessandrofama** [comment]
Hi Bradley, 

For Windows open FMOD Studio first, then the .exe. After that drag a folder containing audio files to the tiny application. Mac OS is broken, haven't kept up with updates.

**Comment by bradleygurwin** [comment]
Thanks for getting back to me Alessandro! Unless I'm missing something, I don't see a .exe in the repo. Is there a file here that should instead function as the executable?

**Comment by alessandrofama** [comment]
It should be here in the releases section of the repo: https://github.com/alessandrofama/FMOD-Audio-Importer/releases/tag/v1.0.0

**Comment by bradleygurwin** [comment]
Oh I see, thanks!
